# Generated by Django 4.1.7 on 2023-03-25 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("team", "0004_personne"),
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("libelle", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="static/photos/")),
                ("dateD", models.DateField(auto_now_add=True)),
                ("dateF", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Planning", "Planning"),
                            ("In progress", "In progress"),
                            ("Reviewing", "Reviewing"),
                            ("Completed", "Completed"),
                        ],
                        default="Planning",
                        max_length=50,
                    ),
                ),
                (
                    "team",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="team.team"
                    ),
                ),
                ("type", models.ManyToManyField(to="services.service")),
            ],
        ),
    ]
