# Generated by Django 4.1.7 on 2023-03-25 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="details",
            field=models.FileField(blank=True, upload_to="static/details/"),
        ),
    ]
