# Generated by Django 4.1.7 on 2023-03-28 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0004_personne"),
        ("portfolio", "0004_alter_project_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="team",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="team.team"
            ),
        ),
    ]
