# Generated by Django 4.1.5 on 2023-04-04 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_project_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='details',
            field=models.FileField(upload_to='static/details/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='static/photos/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Planning', 'Planning'), ('In progress', 'In progress'), ('Reviewing', 'Reviewing'), ('Completed', 'Completed'), ('Suggested', 'Suggested')], default='Suggested', max_length=50),
        ),
    ]
