# Generated by Django 4.1.6 on 2023-04-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0006_alter_project_details_alter_project_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("image", models.ImageField(upload_to="static/photos/")),
                ("body", models.TextField()),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "tags",
                    models.ManyToManyField(
                        choices=[
                            ("Design tools", "Design tools"),
                            ("Design trends", "Design trends"),
                            ("Design inspiration", "Design inspiration"),
                            ("Responsive design", "Responsive design"),
                            ("Web design", "Web design"),
                            ("User experience", "User experience"),
                            ("Branding", "Branding"),
                            ("UI/UX design", "UI/UX design"),
                            ("Animation", "Animation"),
                            ("Graphic design", "Graphic design"),
                            ("User interface", "User interface"),
                            ("Illustration", "Illustration"),
                        ],
                        to="portfolio.tag",
                    ),
                ),
            ],
        ),
    ]
