# Generated by Django 4.1.6 on 2023-04-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0007_tag_article"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="tags",
            field=models.ManyToManyField(blank=True, to="portfolio.tag"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(
                choices=[
                    ("Design trends", "Design trends"),
                    ("Responsive design", "Responsive design"),
                    ("UI/UX design", "UI/UX design"),
                    ("Branding", "Branding"),
                    ("Design inspiration", "Design inspiration"),
                    ("Animation", "Animation"),
                    ("Illustration", "Illustration"),
                    ("Graphic design", "Graphic design"),
                    ("User experience", "User experience"),
                    ("Web design", "Web design"),
                    ("Design tools", "Design tools"),
                    ("User interface", "User interface"),
                ],
                max_length=50,
            ),
        ),
    ]
