# Generated by Django 4.1.5 on 2023-04-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_project_status_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(choices=[('Design tools', 'Design tools'), ('UI/UX design', 'UI/UX design'), ('Web design', 'Web design'), ('Illustration', 'Illustration'), ('Responsive design', 'Responsive design'), ('Animation', 'Animation'), ('Graphic design', 'Graphic design'), ('User experience', 'User experience'), ('User interface', 'User interface'), ('Design inspiration', 'Design inspiration'), ('Branding', 'Branding'), ('Design trends', 'Design trends')], max_length=50),
        ),
    ]
