# Generated by Django 4.1.5 on 2023-04-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(choices=[('Illustration', 'Illustration'), ('User experience', 'User experience'), ('Branding', 'Branding'), ('Design trends', 'Design trends'), ('Responsive design', 'Responsive design'), ('Design inspiration', 'Design inspiration'), ('Animation', 'Animation'), ('Design tools', 'Design tools'), ('Graphic design', 'Graphic design'), ('Web design', 'Web design'), ('User interface', 'User interface'), ('UI/UX design', 'UI/UX design')], max_length=50),
        ),
    ]
