# Generated by Django 4.1.5 on 2023-05-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(choices=[('Web design', 'Web design'), ('UI/UX design', 'UI/UX design'), ('Design tools', 'Design tools'), ('Branding', 'Branding'), ('Graphic design', 'Graphic design'), ('Illustration', 'Illustration'), ('User interface', 'User interface'), ('Design inspiration', 'Design inspiration'), ('Responsive design', 'Responsive design'), ('User experience', 'User experience'), ('Animation', 'Animation'), ('Design trends', 'Design trends')], max_length=50),
        ),
    ]
