# Generated by Django 4.1.7 on 2023-03-25 18:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Personne",
        ),
    ]
