# Generated by Django 4.1.5 on 2023-05-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_personne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
